version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

python:
  install:
    requirements: docs/requirements_docs.txt

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false
